# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/convox/rack"
  version = "20180324152434"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/errwrap"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/ginkgo"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/gomega"
  
[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[override]]
  name = "github.com/fsouza/go-dockerclient"
  branch = "master"
  # version = "v1.2.2"

# This seem to be required due to a problem in either docker or go-dockerclient
# issue is https://github.com/fsouza/go-dockerclient/issues/736#issuecomment-398217187
[[override]]
  name = "github.com/docker/docker"
  branch = "master"
  # revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[[override]]
  name = "github.com/docker/libnetwork"
  branch = "master"

